# Generated by Django 4.0.2 on 2022-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightmoves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesspiece',
            name='colour',
            field=models.CharField(choices=[('w', 'White'), ('b', 'Black')], max_length=1),
        ),
        migrations.AlterField(
            model_name='chesspiece',
            name='type',
            field=models.CharField(choices=[('k', 'King'), ('q', 'Queen'), ('b', 'Bishop'), ('n', 'Knight'), ('r', 'Rook'), ('p', 'Pawn')], max_length=1),
        ),
    ]
