# Generated by Django 4.0.2 on 2022-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knightmoves', '0002_alter_chesspiece_colour_alter_chesspiece_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=2)),
            ],
        ),
    ]
